### ISSUE TITLE
ffmpeg pipe output fails with demos that have spaces in the file name

### ISSUE THREAD

**Issue by entikmag** [entdark/q3mme#5]
Not sure if this is fixable but....testing out pipe output with ffmpeg and ran into this issue. Demos with spaces in the file name will cause ffmpeg to fail when it tries to write the output file, because it reads/writes the name wrong. The ffmpeg solution is to add quotes around %o, but the new issue arises with Quake 3 not being able to parse quotes inside quotes for a cvar.

The overall solution is to rename all files without spaces, which might require renaming software if large demo storage is built up.

**Comment by entdark** [comment]
You can try to use explicit name for the output then just move the file like this:
`ffmpeg -f avi -i - -threads 0 -c:a aac -c:v libx264 -preset ultrafast -y -pix_fmt yuv420p -crf 19 mme/capture/output.mkv 2> ffmpeglog.txt`
Then you need to move that file manually somewhere or rename it else next time it will be overwritten.

**Comment by entdark** [comment]
Fixed in 2196182326d651577d71dfe557d0d8a1566f3bf0 and 22610845805710465f528a14c80207ed04ebdbb0.
